import "./globals.css";

// localt font import
import LocalFont from "next/font/local";

// remote font import
import { Playwrite_NZ } from "next/font/google";
import Header from "@/components/header";

// remote font kurulum
const play = Playwrite_NZ({
  subsets: ["latin"],
  variable: "--font-play",
});

// local font kurulum
const show = LocalFont({
  src: "../assets/Showpop.ttf",
  variable: "--font-show",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased flex flex-col ${play.variable} ${show.variable}`}>
        <Header />

        <main className="flex-1 text-3xl p-10 text-center my-5">{children}</main>
      </body>
    </html>
  );
}
