import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased flex flex-col`}>
        <main className="flex-1 text-3xl p-10 text-center my-5">{children}</main>
      </body>
    </html>
  );
}
